# -*- coding: utf-8 -*-
"""Aula 2 — A lava que mata. Conteudo dos passos."""

AULA = {
 "n": 2,
 "slug": "aula2",
 "titulo": "A lava que mata",
 "subtitulo": "Hoje você escreve o seu primeiro código: uma peça que tira a vida de quem encosta.",
 "tempo": "50 minutos",
 "etiqueta": "Aula 2 · primeiro código",
 "fim": "Acabou a Aula 2. Você escreveu o seu primeiro programa: o Roblox agora reage sozinho a uma coisa que acontece no jogo.",
 "avisos": [
   ("Projeto novo", "Esta aula começa do zero, num projeto novo. Você não precisa do obby da aula passada."),
   ("Atalhos", "Este material usa <span class=ui>Ctrl</span>, do Windows. Num Mac, troque Ctrl por <span class=ui>⌘</span>."),
   ("Travou?", "Todo passo tem um quadro laranja embaixo com o conserto dos erros mais comuns. Procure lá antes de chamar o professor."),
 ],
 "passos": [
  dict(n=1, titulo="Abra o Roblox Studio e escolha BASEPLATE",
    img="comum/c01_tela_inicial.jpg", clipe=None,
    corpo="Abra o Roblox Studio. Na tela que aparece, procure a fileira <b>Abrir um modelo</b> e clique no primeiro quadradinho, o <span class=ui>Baseplate</span>.<br><br>É o mundo mais vazio que existe: só um chão quadriculado. É isso que queremos.",
    ck="Abriu uma tela cinza grande com chão quadriculado e uma plataforma clara no meio. Pode demorar alguns segundos.",
    sos=[("Não acho a fileira dos modelos","Role a página para baixo, ou clique em <span class=ui>Modelos</span> na barra da esquerda."),
         ("Abriu o projeto da aula passada","Feche a aba dele no <b>x</b> e volte para o Início. Hoje é projeto novo."),
         ("Apareceu uma janelinha de Boas-vindas por cima","Clique em <span class=ui>Voltar ao início</span>, o botão da esquerda — ou no <b>✕</b> do canto. Não clique em <span class=ui>Iniciar a introdução</span>.")]),

  dict(n=2, titulo="Prepare o editor (uma vez em cada computador)", img="comum/c06_preparar_editor.jpg", clipe=None,
    corpo="Hoje você vai <b>digitar código</b>, e o Studio vem com duas ajudas que atrapalham quem está aprendendo: ele sugere linhas inteiras e fecha parênteses e aspas sozinho. Vamos desligar as duas.<br><br>No Windows: <span class=ui>Arquivo → Configurações do Studio</span>. No Mac: <span class=ui>Roblox Studio → Configurações do Studio</span>.<br><br><b>1.</b> Na busca escreva <b>assist</b> e desmarque <span class=ui>Ativar assistente de código</span>.<br><b>2.</b> Apague a busca, escreva <b>fechamento</b> e desmarque <span class=ui>Colchetes de fechamento automáticos</span> e <span class=ui>Aspas de fechamento automáticas</span>.<br><br>Feche a janela. Isso fica guardado — só precisa fazer uma vez.",
    ck="As três caixinhas estão <b>vazias</b>: assistente de código, colchetes e aspas.",
    sos=[("Não acho Configurações do Studio","No Windows é o menu <span class=ui>Arquivo</span>, bem no canto de cima à esquerda da janela."),
         ("A busca não acha nada","Escreva só <b>assist</b>, sem acento e sem mais nada."),
         ("Por que desligar?","Ligado, o editor escreve linhas que você não pediu, e o <b>Tab</b> aceita a sugestão em vez de recuar. Desligado, o que está escrito na aula é exatamente o que você digita.")]),

  dict(n=3, titulo="Abra a lista do mundo e vá para a aba MODELO", img="aula2/s03_b.jpg", clipe=None,
    corpo="Na direita fica o <span class=ui>Explorador</span> — a lista de tudo que existe no seu mundo. Ela vem <b>fechada</b>: clique na <b>setinha</b> à esquerda de <span class=ui>Workspace</span> para abrir.<br><br>Depois, na linha de cima, clique na aba <span class=ui>Modelo</span>. <b>Isto é obrigatório</b> — cada aba mostra botões diferentes, e os desta aula só existem nela.",
    ck="Abaixo de Workspace apareceram <span class=ui>SpawnLocation</span> e <span class=ui>Baseplate</span>, e a faixa de cima mostra <span class=ui>Parte</span>, <span class=ui>Material</span>, <span class=ui>Cor</span> e <span class=ui>Âncora</span>.",
    sos=[("Cliquei e a lista fechou de novo","Você clicou duas vezes. Clique uma só."),
         ("Não tenho o Explorador","Aba <span class=ui>Início</span>, botão <span class=ui>Explorador</span>."),
         ("Não acho a aba Modelo","Ela fica entre <span class=ui>Script</span> e <span class=ui>Plugins</span>.")]),

  dict(n=4, titulo="Crie a peça que vai virar lava", img="aula2/s04_b.jpg", clipe="01_criar_peca.gif",
    corpo="Clique em <span class=ui>Parte</span> — <b>no desenho, não na palavra embaixo dele</b>.<br><br>Clicar na palavra não faz absolutamente nada. É o erro mais comum.",
    ck="Nasceu um bloco cinza no meio do mundo <b>e</b> a palavra <span class=ui>Part</span> apareceu na lista da direita.",
    sos=[("Cliquei e não aconteceu nada","Você clicou na palavra. Clique no <b>desenho</b> acima dela."),
         ("Apareceu Part na lista mas eu não vejo a peça","É o próximo passo. Calma."),
         ("Criei duas sem querer","Aperte <b>Ctrl + Z</b>. Desfaz a última coisa.")]),

  dict(n=5, titulo="Leve a câmera até a peça", img="aula2/p05_camera.jpg", clipe=None,
    corpo="Clique na palavra <span class=ui>Part</span> na lista da direita. Depois <b>leve o mouse para cima do mundo 3D</b> (o cinza grande) e aperte a tecla <b>F</b> — se o mouse ficar na lista, o F começa a renomear a peça em vez de mover a câmera.<br><br>A câmera voa até a peça. Depois use a tecla <b>S</b> algumas vezes para afastar um pouco — a peça fica grande demais logo depois do F.",
    ck="A peça está no meio da tela, num tamanho que dá para ver o chão em volta.",
    sos=[("Apertei F e nada","O mouse precisa estar em cima do mundo 3D quando você aperta F, não em cima da lista."),
         ("A peça virou um nome escrito na lista","Você apertou F com a lista selecionada e começou a renomear. Aperte <b>Esc</b> e tente de novo.")]),

  dict(n=6, titulo="Ancore a peça", img="aula2/s06_b.jpg", clipe="02_ancorar.gif",
    corpo="Com a peça ainda selecionada, clique em <span class=ui>Âncora</span>.<br><br><b>Âncora prende a peça no ar.</b> Peça sem âncora despenca no segundo em que o jogo começa.<br><br>A regra do dia: <b>criou, ancorou.</b>",
    ck="O botão <span class=ui>Âncora</span> ficou aceso, com um fundo mais claro que os outros.",
    sos=[("Como sei se ancorou?","Na lista de <span class=ui>Propriedades</span>, embaixo à direita, digite <b>anchor</b> na caixa de busca. A caixinha <span class=ui>Anchored</span> fica marcada."),
         ("A peça não está selecionada","Clique no nome <span class=ui>Part</span> na lista da direita. Selecionada = com borda azul em volta.")]),

  dict(n=7, titulo="Pinte de vermelho", img="aula2/s07_e.jpg", clipe="03_cor.gif",
    corpo="São <b>três cliques</b>, nesta ordem:<br><br><b>1.</b> Clique na <b>setinha</b> ao lado do círculo colorido do botão <span class=ui>Cor</span>. Abre um painel de hexágonos.<br><b>2.</b> Clique num hexágono vermelho. O painel fecha.<br><b>3.</b> Clique <b>no círculo do botão Cor</b>. É esse clique que pinta.",
    ck="A peça ficou vermelha.",
    sos=[("Escolhi a cor e a peça não mudou","Falta o clique no círculo do botão Cor. Escolher no painel só separa a cor; quem pinta é o botão."),
         ("Cliquei no círculo e mesmo assim não pinta","No rodapé do painel de cores existe um interruptor <i>“Clique no objeto para aplicar a cor”</i>. Ele precisa ficar <b>desligado</b> (cinza)."),
         ("Pintou a peça errada","<b>Ctrl + Z</b>, clique na peça certa e repita.")]),

  dict(n=8, titulo="Deixe a lava brilhando", img="aula2/s08_e.jpg", clipe="04_material_neon.gif",
    corpo="Clique na <b>setinha</b> ao lado do botão <span class=ui>Material</span>.<br><br>No alto do painel tem a caixa <span class=ui>Pesquisar materiais</span>. Clique dentro dela — fica com <b>borda azul</b> — e escreva <b>neon</b>. Sobra uma bolinha só. Clique nela.",
    ck="A peça passou a brilhar, como se tivesse luz por dentro.",
    sos=[("Escrevi e não filtrou nada","A caixa já tinha texto guardado. Clique no <b>⊗</b> do lado direito para limpar e escreva de novo."),
         ("Escrevi e a tela se mexeu sozinha","A caixa não estava com o foco, então as letras foram para o mundo 3D (a letra <b>e</b> sobe a câmera). Clique <b>dentro</b> da caixa, veja a borda azul, e só então escreva.")]),

  dict(n=9, titulo="Dê o nome de LAVA para a peça", img="aula2/s09_b.jpg", clipe="05_renomear.gif",
    corpo="Na lista da direita, clique com o <b>botão direito</b> em cima de <span class=ui>Part</span> e escolha <span class=ui>Renomear</span>.<br><br>Escreva <b>Lava</b> e aperte <b>Enter</b>.<br><br>O nome não muda nada no jogo — muda tudo para você, que daqui a pouco vai ter várias peças.",
    ck="Na lista está escrito <span class=ui>Lava</span> no lugar de <span class=ui>Part</span>.",
    sos=[("O nome voltou para Part","Você apertou Esc em vez de Enter. Repita e termine com <b>Enter</b>."),
         ("Escrevi errado","Botão direito no nome, <span class=ui>Renomear</span> de novo.")]),

  dict(n=10, titulo="Coloque um SCRIPT dentro da lava", img="aula2/s10_c.jpg", clipe="06_inserir_script.gif",
    corpo="Clique uma vez em <span class=ui>Lava</span> na lista. Aparece um <b>+</b> logo depois do nome. Clique nesse <b>+</b>.<br><br>Abre uma listinha. Clique em <span class=ui>Script</span>.<br><br>Um <b>script</b> é um papel com instruções. O Roblox lê esse papel e faz o que está escrito.",
    ck="Abriu uma tela escura cheia de texto, e na lista apareceu <span class=ui>Script</span> <b>logo abaixo e um pouco para dentro</b> de <span class=ui>Lava</span>.",
    sos=[("O Script apareceu fora da Lava","Ele precisa estar <b>dentro</b> dela. Arraste o <span class=ui>Script</span> por cima da palavra <span class=ui>Lava</span> na lista, ou apague e refaça com a Lava selecionada."),
         ("Não aparece o +","Clique uma vez na linha da Lava primeiro. O + só aparece na linha selecionada."),
         ("Entrou outra coisa (Decal, Folder…)","Você clicou no item errado da listinha. Apague com <b>Delete</b> e faça de novo.")]),

  dict(n=11, titulo="Olhe o que veio escrito", img="aula2/p11_editor_nasce.jpg", clipe=None,
    corpo="Todo script novo já vem com uma linha pronta:<br><br><span class=ui>print(\"Hello world!\")</span><br><br>Isso só escreve um texto para o programador ver. Não serve para nós.<br><br><b>Apague essa linha inteira.</b> Clique no fim dela e segure <b>Backspace</b> até a linha 1 ficar vazia.",
    ck="A linha 1 está vazia. Não sobrou nenhuma letra.",
    sos=[("Apaguei demais e sumiu tudo","Tudo bem — era para ficar vazio mesmo."),
         ("Não acho a tela do script","Lá em cima, do lado da aba <span class=ui>Place1</span>, tem outra aba escrita <span class=ui>Script</span>. Clique nela.")]),

  dict(n=12, titulo="Escreva a primeira linha", img="aula2/p12_linha1.jpg", clipe=None,
    codigo="local lava = script.Parent",
    corpo="Escreva exatamente isto na linha 1:",
    depois="<b>O que essa linha faz:</b> ela dá o apelido <b>lava</b> para a peça onde o script mora. <span class=ui>script.Parent</span> quer dizer “a peça que está segurando este papel”.<br><br>Daqui para a frente, escrever <b>lava</b> é a mesma coisa que escrever “a peça vermelha”.",
    ck="A palavra <span class=ui>local</span> ficou de outra cor e não apareceu nenhum risco vermelho embaixo.",
    sos=[("Apareceu um risco vermelho","Alguma letra está errada. Confira: <b>l</b> minúsculo em local, ponto entre script e Parent, <b>P</b> maiúsculo em Parent."),
         ("O editor completou sozinho","O Studio sugere palavras enquanto você digita. Aperte <b>Esc</b> para dispensar a sugestão e continue."),
         ("Apareceu uma caixinha cinza com sugestões","É o editor tentando adivinhar. Aperte <b>Esc</b> para fechá-la e continue digitando. Se você apertar <b>Enter</b> com ela aberta, ele escreve a sugestão no lugar do que você ia escrever.")]),

  dict(n=13, titulo="Escreva o resto do código", img="aula2/p13_codigo_pronto.jpg", clipe=None,
    codigo='local lava = script.Parent\n\nlava.Touched:Connect(function(parte)\n\tlocal humano = parte.Parent:FindFirstChild("Humanoid")\n\tif humano then\n\t\thumano.Health = 0\n\tend\nend)',
    auto=(7, 8),
    corpo="Pule uma linha e escreva o resto. O código inteiro fica assim:",
    depois="<b>Duas coisas que economizam briga:</b><br><br>Não digite os dois <span class=ui>end</span> do fim — estão em cinza porque o <b>editor escreve sozinho</b>, no instante em que você aperta Enter depois da linha do <span class=ui>function(</span> e depois da linha do <span class=ui>then</span>.<br><br>Não aperte <b>Tab</b>. O editor já empurra as linhas para dentro sozinho.",
    ck="O código tem 8 linhas, as linhas de dentro estão recuadas como na foto, e não sobrou nenhum risco vermelho.",
    sos=[("Sobraram end a mais","Você digitou os que o editor já tinha escrito. Apague os extras até sobrar <b>um</b> <span class=ui>end</span> e <b>um</b> <span class=ui>end)</span>."),
         ("Apertei Tab e apareceu código que eu não escrevi","Era a sugestão do assistente. <b>Ctrl + Z</b> para desfazer, e refaça o passo 2 desta aula."),
         ("Risco vermelho no fim","Conte os fechamentos: um <span class=ui>end</span> para o <span class=ui>if</span> e um <span class=ui>end)</span> para o <span class=ui>function</span>."),
         ("Escrevi Humanoid errado","Tem que ser exatamente <span class=ui>\"Humanoid\"</span>, com H maiúsculo e entre aspas."),
         ("Apareceu uma caixinha cinza com sugestões","É o editor tentando adivinhar. Aperte <b>Esc</b> para fechá-la e continue digitando. Se você apertar <b>Enter</b> com ela aberta, ele escreve a sugestão no lugar do que você ia escrever."),
         ("A aspa saiu errada (Ï, ä, ou duas aspas juntas)","A aspa do teclado brasileiro é <b>tecla muda</b>. Antes de vogal ela vira trema; no fim da linha ela às vezes dobra. O conserto é sempre o mesmo: apague o que saiu errado e digite a aspa <b>seguida da barra de espaço</b>. Sai uma aspa limpa, sem espaço.")]),

  dict(n=14, titulo="Entenda o que você escreveu", img="aula2/p13_codigo_pronto.jpg", clipe=None,
    corpo="Leia em voz alta, linha por linha:<br><br><b>lava.Touched:Connect(...)</b> — “quando alguém <b>encostar</b> na lava, faça isto”.<br><br><b>function(parte)</b> — “isto” começa aqui. <span class=ui>parte</span> é o pedaço que encostou (um pé, uma mão).<br><br><b>parte.Parent:FindFirstChild(\"Humanoid\")</b> — “procure, no dono desse pedaço, uma coisa chamada Humanoid”. Humanoid é o que faz um boneco ser um boneco vivo.<br><br><b>if humano then</b> — “se achou mesmo um boneco…”<br><br><b>humano.Health = 0</b> — “…a vida dele vira zero”.<br><br>Essa procura existe por um motivo: se uma pedra cair na lava, não tem Humanoid nenhum, e o código não quebra.",
    ck="Você consegue explicar para o colega do lado o que a linha <span class=ui>humano.Health = 0</span> faz.",
    sos=[("Não entendi o Parent","<span class=ui>Parent</span> é “quem está segurando”. O pé está dentro do boneco: o Parent do pé é o boneco."),
         ("Por que não é só parte.Health = 0?","Porque quem tem vida é o boneco inteiro, não o pé.")]),

  dict(n=15, titulo="Volte para o mundo", img="aula2/s14_b.jpg", clipe="07_voltar_ao_mundo.gif",
    corpo="Lá em cima, do lado esquerdo, existem duas abas: <span class=ui>Place1</span> e <span class=ui>Script</span>.<br><br>Clique em <span class=ui>Place1</span> para voltar a ver o mundo 3D. O script continua lá, salvo, mesmo com a aba fechada.",
    ck="Você está vendo o chão e a peça vermelha de novo.",
    sos=[("Fechei a aba do Script sem querer","Não perdeu nada. Clique duas vezes em <span class=ui>Script</span> na lista da direita para abrir de novo.")]),

  dict(n=16, titulo="Jogue", img="aula2/s15_b.jpg", clipe="08_jogar.gif",
    corpo="Aperte o <b>▶</b> azul, no canto superior esquerdo.<br><br>O Studio vira o jogo: nasce um boneco e você anda com <b>W A S D</b>, pula com <b>espaço</b>.",
    ck="Apareceu um boneco no mundo e as abas de cima mudaram para <span class=ui>Cliente</span> e <span class=ui>Servidor</span>.",
    sos=[("Não acho o botão ▶","É o triângulo azul no alto à esquerda, ao lado da palavra <span class=ui>Teste</span>. Não é a palavra Teste — é o triângulo."),
         ("Demora muito","Na primeira vez leva uns 10 segundos. É normal.")]),

  dict(n=17, titulo="Encoste na lava", img="aula2/p16_no_jogo.jpg", clipe=None,
    corpo="Ande com <b>W</b> até pisar na peça vermelha.<br><br>No instante em que o seu pé encosta, o boneco morre e nasce de novo.",
    ck="O boneco caiu no chão e voltou a nascer. Se você ficar em cima da lava, ele morre de novo, sem parar.",
    sos=[("Encostei e não morri","Três coisas para conferir, nessa ordem: <b>1)</b> o Script está <b>dentro</b> da Lava na lista? <b>2)</b> sobrou algum risco vermelho no código? <b>3)</b> você parou o jogo e voltou a jogar depois de escrever o código?"),
         ("Morri antes de encostar","Você nasceu em cima da lava. Pare o jogo, arraste a lava para longe da plataforma clara e jogue de novo."),
         ("O boneco não anda","Clique uma vez dentro da tela do jogo antes de usar W A S D.")]),

  dict(n=18, titulo="Pare o jogo", img="aula2/s17_b.jpg", clipe="09_parar.gif",
    corpo="Aperte o <b>quadrado vermelho</b>, do lado do ▶.<br><br><b>Isto é importante:</b> tudo o que você construir com o jogo rodando some quando o jogo para. Só vale o que você faz com o jogo <b>parado</b>.",
    ck="Voltou a tela de montar, com a lista da direita mostrando <span class=ui>Workspace</span> de novo.",
    sos=[("Continuo no jogo","Aperte o quadrado vermelho, não o ▶."),
         ("Sumiu a minha lava!","Você a criou com o jogo rodando. Refaça com o jogo parado — é a regra que mais pega gente.")]),

  dict(n=19, titulo="Salve", img="aula2/s17_b.jpg", clipe=None,
    corpo="Aperte <b>Ctrl + S</b>. Ele pergunta onde salvar: escolha <span class=ui>Salvar em arquivo</span> e dê o nome <b>lava</b>.<br><br>Guarde numa pasta que você lembre. Na próxima aula começamos outro projeto do zero, mas este é seu.",
    ck="O nome da aba lá em cima deixou de ter um pontinho de “não salvo”.",
    sos=[("Pediu para publicar na Roblox","Escolha <b>Salvar em arquivo</b>, não “Salvar na Roblox”. Publicar é assunto da Aula 4."),
         ("Não sei onde salvei","Salve de novo em <b>Área de Trabalho</b>. Fica fácil de achar.")]),
 ],
}
